export function renderManualPage(topic?: string): string | null {
  const normalized = (topic ?? "").trim().toLowerCase();

  switch (normalized) {
    case "":
    case "help":
      return [
        "GSV manual pages",
        "",
        "Available pages:",
        "  gsv   Platform model, targets, paths, and knowledge systems",
        "  codemode  Run GSV tool scripts from the shell",
        "  proc  Process inspection and same-owner process IPC",
        "  sched  Kernel schedules for process work",
        "  notify  User notifications and background job alerts",
        "  wiki  Durable knowledge databases, including the personal wiki",
        "",
        "Usage:",
        "  man gsv",
        "  man codemode",
        "  man proc",
        "  man sched",
        "  man notify",
        "  man wiki",
        "",
      ].join("\n");

    case "sched":
      return [
        "SCHED(1)",
        "",
        "NAME",
        "  sched - manage Kernel schedules",
        "",
        "SYNOPSIS",
        "  sched list [--all]",
        "  sched add --name NAME (--cron EXPR [--timezone TZ] | --every DURATION | --after DURATION | --at TIME) [--pid PID] [--conversation id] <prompt/message>",
        "  sched add --json JSON",
        "  sched enable <id>",
        "  sched disable <id>",
        "  sched remove <id>",
        "  sched run <id> [--force]",
        "",
        "OVERVIEW",
        "  `sched` wraps the sched.* syscalls. Without --pid, add spawns a",
        "  scheduled process. With --pid, add delivers a process event to an",
        "  existing process conversation.",
        "",
        "EXPRESSIONS",
        "  --cron uses five Linux-style fields and an IANA timezone.",
        "  --every, --after, and proc call --timeout durations support ms, s, m, h, and d.",
        "",
      ].join("\n");

    case "proc":
      return [
        "PROC(1)",
        "",
        "NAME",
        "  proc - inspect processes and send same-owner process messages",
        "",
        "SYNOPSIS",
        "  proc self",
        "  proc list",
        "  proc segments [--pid PID] [--conversation id]",
        "  proc policy [--pid PID] [--conversation id] [--overflow manual|auto-compact|fail] [--compact-at N] [--keep-last N]",
        "  proc segment <segment-id> [--pid PID] [--conversation id] [--limit N] [--offset N] [--json]",
        "  proc compact [--pid PID] [--conversation id] (--keep-last N | --through-message-id ID) [--summary TEXT | --generate-summary]",
        "  proc fork (<segment-id> | --message-id ID) [--pid PID] [--conversation id] [--target id] [--title TITLE] [--segment-only]",
        "  proc send <pid> [--conversation id] [--metadata-json json] <message>",
        "  proc call <pid> [--conversation id] [--metadata-json json] [--timeout 60s] <message>",
        "",
        "OVERVIEW",
        "  `proc` is the process IPC userland command. It wraps proc.ipc syscalls instead",
        "  of exposing a model-specific ProcessMessage tool.",
        "",
        "COMMANDS",
        "  self",
        "      Print the current GSV process id. The same value is available as $GSV_PID.",
        "  list",
        "      Show processes visible to the current user.",
        "  segments",
        "      List compacted conversation archive segments for a process conversation.",
        "  policy",
        "      Show or set the visible context-overflow policy for a conversation.",
        "  segment",
        "      Read archived messages from a compacted segment without restoring them.",
        "  compact",
        "      Archive a conversation prefix and replace it with a visible summary marker.",
        "  fork",
        "      Branch a live conversation from a message or restore a compacted segment",
        "      into a new conversation.",
        "  send",
        "      Send asynchronous mail to another process owned by the same user.",
        "  call",
        "      Send bounded work to another process. The kernel delivers ipc.reply or",
        "      ipc.timeout back to the caller's default conversation.",
        "",
        "OPTIONS",
        "  --conversation <id>      Target process conversation. Defaults to default.",
        "  --pid <pid>              Target process for lifecycle commands. Defaults to this process.",
        "  --keep-last <n>          Compact all but the newest n messages.",
        "  --through-message-id <id> Compact through a specific message id.",
        "  --summary <text>         Markdown summary inserted into the live conversation.",
        "  --generate-summary       Ask the process model to write the compact summary.",
        "  --overflow <mode>        Policy mode: manual, auto-compact, or fail.",
        "  --compact-at <n>         Policy pressure threshold from 0 to 1.",
        "  --target <id>            Conversation id to create for proc fork.",
        "  --message-id <id>        Live message id to branch from with proc fork.",
        "  --segment-only           Fork only the archived segment, without the kept suffix.",
        "  --limit <n>              Maximum archived messages to print for proc segment.",
        "  --offset <n>             Archived message offset for proc segment.",
        "  --json                   Print raw JSON for proc segment.",
        "  --metadata-json <json>   Optional JSON object delivered with the message.",
        "  --timeout <duration>     Call deadline. Supports ms, s, and m suffixes.",
        "",
      ].join("\n");

    case "codemode":
      return [
        "CODEMODE(1)",
        "",
        "NAME",
        "  codemode - run JavaScript blocks with GSV shell and filesystem wrappers",
        "",
        "SYNOPSIS",
        "  codemode <script.js> [options] [-- argv...]",
        "  codemode run <script.js> [options] [-- argv...]",
        "  codemode -e <code> [options] [-- argv...]",
        "",
        "OVERVIEW",
        "  `codemode` runs one async JavaScript block through the same CodeMode runtime exposed",
        "  to agents. Scripts can call `await shell(input, options)` and `fs.read`, `fs.write`,",
        "  `fs.edit`, `fs.delete`, or `fs.search`.",
        "  Script files and -e code are treated as async function bodies. Use top-level await",
        "  freely, and use an explicit return statement for the value to print.",
        "",
        "OPTIONS",
        "  --target <device>   Default target for shell and filesystem calls.",
        "  --cwd <path>        Default cwd for shell calls and relative filesystem paths.",
        "  --json              Print the full result envelope.",
        "  --arg key=value     Expose scalar args[key] to the script.",
        "  --args-json <json>  Expose structured args to the script.",
        "",
        "SCRIPT CONTEXT",
        "  argv                Positional arguments after `--`.",
        "  args                Values supplied with --arg or --args-json.",
        "  shell(input, opts)  Run or continue a shell command.",
        "  fs                  Filesystem helpers: read, write, edit, delete, search.",
        "",
        "RESULTS",
        "  Without --json, completed runs print only the returned value.",
        "  With --json, runs print { status, result?, error?, logs? }.",
        "  Failed runs exit 1.",
        "",
        "EXAMPLES",
        "  codemode -e 'return await shell(\"pwd\")'",
        "  codemode ./check.js --cwd ~/projects/gsv -- arg1 arg2",
        "",
      ].join("\n");

    case "gsv":
      return [
        "GSV(1)",
        "",
        "NAME",
        "  gsv - distributed AI operating environment",
        "",
        "OVERVIEW",
        "  GSV gives AI processes a Linux-like filesystem, explicit tools, and multiple execution targets.",
        "  `gsv` is the local control target. Other targets are user devices or nodes that may expose",
        "  shell and filesystem operations when they are online and authorized.",
        "",
        "STANDING CONTEXT",
        "  ~/context.d/*.md",
        "      Small curated notes that are always loaded into prompt context.",
        "",
        "DURABLE KNOWLEDGE",
        "  ~/knowledge/",
        "      Durable markdown knowledge pages. This is not loaded into the prompt automatically.",
        "      Use `wiki` for both broader knowledge bases and the conventional `personal` database.",
        "",
        "KNOWN PATHS",
        "  /home/<user>   User home, including standing context and durable knowledge",
        "  /workspaces    Task workspaces and user artifacts",
        "  /var           Runtime-managed state, caches, and generated system data",
        "  /etc           System manuals and stable operator documentation",
        "  /sys           Live kernel configuration and runtime control surfaces",
        "  /proc          Live process and runtime inspection surfaces",
        "  /dev           Device-like virtual endpoints",
        "",
        "KNOWLEDGE WORKFLOWS",
        "  Use direct page writes when the target note is clear and the information is durable.",
        "  Use inbox staging when the information is tentative, uncertain, or needs review.",
        "  Use `search` to find candidate notes and `query` when you want a compact brief with references.",
        "",
      ].join("\n");

    case "wiki":
      return [
        "WIKI(1)",
        "",
        "NAME",
        "  wiki - manage durable knowledge databases",
        "",
        "OVERVIEW",
        "  `wiki` is provided by the Wiki package. It manages named knowledge databases made of markdown pages and live source references.",
        "  Use it for broader domain knowledge, research notes, product docs, and the conventional `personal` database.",
        "",
        "SEARCH VS QUERY",
        "  wiki search <query> [--prefix PREFIX]",
        "      Find matching notes with snippets.",
        "  wiki query <query> [--prefix PREFIX ...]",
        "      Return a compact brief and references from the best matching notes.",
        "",
        "DATABASE SETUP",
        "  wiki db init product-alpha --title \"Product Alpha\"",
        "  wiki db init personal --title \"Personal\"",
        "",
        "DIRECT PAGE WRITES",
        "  wiki write product-alpha/pages/auth.md --text \"# Auth\\n\\n## Summary\\nCurrent auth model.\"",
        "  wiki write personal/pages/people/alice.md --text \"# Alice\\n\\n## Preferences\\n- Prefers concise replies\"",
        "",
        "LIVE SOURCES",
        "  Source references use the form:",
        "    target:/absolute/path::Optional title",
        "  Quote the whole value when the title contains spaces.",
        "  Example:",
        "    wiki source add product-alpha/pages/auth.md --source \"gsv:/workspaces/gsv/specs/auth.md::Auth spec\"",
        "",
        "INGEST AND COMPILE",
        "  Use ingest when you want to stage or create a page from one or more live sources.",
        "  Example:",
        "    wiki ingest product-alpha --source \"gsv:/workspaces/gsv/docs/alpha-plan.md::Alpha plan\" --title \"Adapter UX inputs\"",
        "    wiki list product-alpha/inbox -r",
        "    wiki compile product-alpha product-alpha/inbox/<candidate>.md product-alpha/pages/adapter-ux.md",
        "",
        "PERSONAL KNOWLEDGE",
        "  Use the `personal` database for durable notes about the user, people, projects, and other standing context.",
        "  Examples:",
        "    wiki query \"What should I remember about Alice?\" --prefix personal/pages",
        "    wiki ingest personal --source \"gsv:/workspaces/chat/alice.md::Alice onboarding notes\"",
        "    wiki compile personal personal/inbox/<candidate>.md personal/pages/people/alice.md",
        "",
      ].join("\n");

    case "notify":
      return [
        "NOTIFY(1)",
        "",
        "NAME",
        "  notify - send and manage user notifications",
        "",
        "OVERVIEW",
        "  `notify` creates durable user notifications and manages their read/dismissed state.",
        "  Notifications appear in the web shell toast/panel and can be delivered by other surfaces later.",
        "",
        "SEND",
        "  notify send --title \"Wiki build finished\" --body \"product-alpha is ready\" --level success",
        "",
        "LIST",
        "  notify list",
        "  notify list --unread",
        "  notify list --dismissed",
        "",
        "STATE CHANGES",
        "  notify read <notification-id>",
        "  notify dismiss <notification-id>",
        "",
        "LEVELS",
        "  info, success, warning, error",
        "",
      ].join("\n");

    default:
      return null;
  }
}
